### ISSUE TITLE
getting various errors when uploading 2 har files 

### ISSUE THREAD

**Issue by kmaqsudi** [sitespeedio/compare#100]
attached HAR files are from sitespeed.io waterfall tab (export HAR).   uploading to compare.sitespeed.io gives error "Cannot read property ‘time’ of undefined'. 

[HAR-file.zip](https://github.com/sitespeedio/compare/files/4032128/HAR-file.zip)

**Comment by soulgalore** [comment]
Hi @kmaqsudi thanks for creating the issue and sharing the HARs that helps so much! I've pushed a fix. It was broken when I added the filmstrip capability but it didn't work if you didn't have any screenshots.

I've tried and it worked for me but please verify that it works for you (make sure that the page is updated).

Best
Peter

**Comment by kmaqsudi** [comment]
confirmed that it works when dropping HARs manually.  Thanks again @soulgalore

**Comment by xmo-odoo** [comment]
@kmaqsudi I've the same issue when generating HARs using Firefox's devtools (on Firefox Developer Edition, so currently 78.0b4) e.g. trying to upload either file from [hars.zip](https://github.com/sitespeedio/compare/files/4750579/hars.zip) displays:
> can't access property "indexOf", e.response.content.mimeType is undefined

**Comment by kmaqsudi** [comment]
have not tried hars from firefox.  have you tried the same using chrome?

**Comment by xmo-odoo** [comment]
> have not tried hars from firefox. have you tried the same using chrome?

It seems to work fine (using firefox to load a chrome har). Doesn't help with FF hars though.

**Comment by soulgalore** [comment]
@xmo-odoo can you share one of the HAR files that fail and I'll fix it!

**Comment by xmo-odoo** [comment]
@soulgalore I put them in the original comment, though the link's probably easy to miss.

https://github.com/sitespeedio/compare/files/4750579/hars.zip

**Comment by soulgalore** [comment]
Ah sorry, let me fix this first thing tomorrow.

**Comment by xmo-odoo** [comment]
> Ah sorry, let me fix this first thing tomorrow.

No worries, it's really not pressing.

**Comment by soulgalore** [comment]
Hi @xmo-odoo sorry it took some time. The HAR is broken (you can test it at http://www.softwareishard.com/har/viewer/). Is it from Firefox directly? If so, can you create an upstream issue at Mozilla. Also the error we got comes from PerfCascade, but I need to look into if there's a way to fix that.

**Comment by xmo-odoo** [comment]
> Hi @xmo-odoo sorry it took some time. The HAR is broken (you can test it at http://www.softwareishard.com/har/viewer/). Is it from Firefox directly? If so, can you create an upstream issue at Mozilla.

Pretty sure it did yeah. It's FDE but it should not break anything. I'll check their bug tracker, thanks for the help (and harviewer to validate har files).
