### ISSUE TITLE
Error parsing WebPageTest HAR file

### ISSUE THREAD

**Issue by franjohn21** [sitespeedio/compare#103]
Hey there -- 

I'm consistently getting an error `Cannot read property 'totalBlockingTime' of undefined` when trying to use this tool for parsing HAR files generated from WebPageTest. Example HAR file: https://gist.github.com/franjohn21/3e3e054150ed5545f59c4f47bc8eb366

**Comment by soulgalore** [comment]
Ah thanks @franjohn21 let me fix that tonight.

**Comment by soulgalore** [comment]
This works for me now, can verify when you have time @franjohn21 that also works for you? Make sure that the application is updated/refreshed.

**Comment by franjohn21** [comment]
👍 Works for me. Appreciate it
