### ISSUE TITLE
Screenshot Image URL 

### ISSUE THREAD

**Issue by SunnyGurnani** [sitespeedio/compare#108]
**Compare is looking for screenshot image at** 
pages/<page>/data/screenshots/1.png

**Whereas SiteSpeed.io is storing screenshots at following.**
pages/<page>/data/screenshots/1/afterPageCompleteCheck.png

**To replicate use following URL to compare.**
https://dobermanv2.s3-us-west-2.amazonaws.com/sitespeed-result/2020/10/19/xGIVIfF4e-control/pages/www.realtor.com/data/browsertime.har

**Comment by soulgalore** [comment]
Ah thank you @SunnyGurnani for reporting! When I refactored that I missed to update the meta-link that is generated in sitespeed.io. I've pushed a PR, when it pass I'll do a new release of sitespeed.io to fix it.

**Comment by soulgalore** [comment]
This should be fixed.
