### ISSUE TITLE
WebPageTest HAR files cannot be compared

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/compare#14]
Example HAR: https://gist.github.com/soulgalore/bfe2be5916f85c2a6d4b34f3be285b92

<img width="483" alt="screen shot 2018-02-13 at 9 02 20 am" src="https://user-images.githubusercontent.com/540757/36139118-a1a85ee8-109c-11e8-9b6c-29c80810a640.png">

**Comment by soulgalore** [comment]
This is a bug in PerfCascade: https://github.com/micmro/PerfCascade/issues/217

**Comment by micmro** [comment]
Look into it tonight.

**Comment by micmro** [comment]
fixed with `v2.2.2` release

**Comment by soulgalore** [comment]
thanks @micmro  upgraded and pushed the release
