### ISSUE TITLE
[Feature] Allow for Github Gist integration

### ISSUE THREAD

**Issue by Nooshu** [sitespeedio/compare#34]
This is more of a feature request than an issue. I've just been using compare and have been sharing results with my team using the following URL structure:

`https://compare.sitespeed.io/?har1=https://www.url.com/browsertime1.har&har1=https://www.url.com/browsertime2.har&compare=1'

This works really well. I'm wondering if it would be helpful to allow compare to parse a JSON file hosted in a Github Gist. That way additional parameters could also be passed in. This is how the Lighthouse viewer works. E.g: [Gist URL](https://gist.github.com/Nooshu/8f2e712a0d4726975a9a271cc1bfe48a) / [Lighthouse report](https://googlechrome.github.io/lighthouse/viewer/?gist=8f2e712a0d4726975a9a271cc1bfe48a). Note the use of `?gist=...`

`https://compare.sitespeed.io/?gist=975a9a271cc1bfe48a...` 

This would shorten the URL being shared and also allow for additional settings to be passed through. For example instead of it saying "HAR1" and "HAR2", a custom label could be added:

```js
{
	"har1": {
		"url": "https://www.url.com/browsertime1.har",
		"label": "Before change"
	},
	"har2": {
		"url": "https://www.url.com/browsertime2.har",
		"label": "After change"
	}
	//...
}
```

![screen shot 2018-10-18 at 08 35 21](https://user-images.githubusercontent.com/1223960/47138267-d0906080-d2b0-11e8-81da-0a77439c4072.png)

I'm sure there are more use cases for this pattern too.

**Comment by soulgalore** [comment]
Hi @Nooshu thanks for sharing! Ah gist would be nice. I haven't thought about it before but that could be a nice thing. Let me have go at it in a couple of days.

About the label: Yep we should have that too. We can start by adding a extra parameter so you can add it yourself from the outside and the we can integrate it in the gist when we have it.

Really cool ideas. I'll ping you when I had some time to do it, then you can help me try it out?

Best
Peter

**Comment by Nooshu** [comment]
Thanks @soulgalore, sounds great. More than happy to help.

**Comment by soulgalore** [comment]
Hi @Nooshu I actually pushed some changes now, you can try it out with https://compare.sitespeed.io/?gist=94e4d997a78e03b32b939fcea63eae8e

I added one more thing, an optional comment field. I'm not 100% sure though. What's missing from my part is to also add choosing run/page in the HAR in the gist (right now it uses the first one in the HAR file). However I wanna clean up the code first, there's a lot we can do better :)

Do you think about something else that we should add?

Best
Peter

**Comment by Nooshu** [comment]
Hey Peter,
Wow that was a quick turn around! I've just tested it and it works well:

[Gist](https://gist.github.com/Nooshu/8f3c5f5876971715df3f1e08fb2ead8a) | [Compare](https://compare.sitespeed.io/?gist=8f3c5f5876971715df3f1e08fb2ead8a)

I noticed HAR 1 / Har 2 are still listed on the visual graph, It is a minor point though:

![screen shot 2018-10-18 at 22 20 56](https://user-images.githubusercontent.com/1223960/47185059-500b4780-d324-11e8-9d5e-33f7ad70cbfa.png)

Love the addition of the comment field. I wonder if there could be a comment for each section? E.g. one at the top as an overall comment for the whole comparison one under waterfall for waterfall comments etc, the same for Visual Progress and Domains too. It may be that they don't get used, it just adds a lot more flexibility:

```
{
	"har1": {
		"url": "...",
		"label": "...",
		"run": "..."
	},
	"har2": {
		"url": "...",
		"label": "...",
		"run": "..."
	},
	"comments": {
		"intro": "Intro comment at the top of the page",
		"waterfall": "Comment for waterfall section",
		"visualprogress": "Visual Progress comment",
		"domains": "Domains comment"
	}
}
```
Adding the run parameter in there as you mention again also allows for more flexibility, since there can be such a big variance between runs.

The last thing I can think of is adding a feature that the lighthouse viewer has. It monitors the clipboard for a GitHub Gist URL. When you paste into the browser window it will pick up the gist string and do the rest for you. Very convenient, but not a high priority at the moment :)

Awesome work, and fantastic tool! I'll be using it in a few presentations in the coming weeks.

**Comment by soulgalore** [comment]
@Nooshu cool I've fixed the Visual Progress label this morning, thanks for noticing. I've also added the clipboard functionality, need to add docs for it. You can paste the Gist id or a HAR JSON.  For the extra comments, let me think about that :)

Let me know if you can share a screenshot from the presentation, always interesting to see!

I also want to add one more thing in the future, following the gist JSON structure. We could make the URL configurable to fetch that JSON, that way it would be nice when you run in CI to match before and after a commit. The CI can generate the JSON on the fly and we could potentially highlight changes in the output between runs (like a regression in one metric would highlight that section). So many cool things you could do :)

**Comment by Nooshu** [comment]
Hi @soulgalore, excellent stuff! I will have a test today. Great idea around the CI process, I hadn't considered the advantages in the automated side of testing.

**Comment by Nooshu** [comment]
Another small addition I've just thought of when handling many tabs is the ability to add a prefix to the page title. E.g Custom Title - Compare HAR files. As at the moment I have many tabs open that all say "Compare HAR files".

**Comment by soulgalore** [comment]
Let me clean up the code during the weekend+ so it's easier for everyone to make changes. Then we can start to add more things :)

**Comment by Nooshu** [comment]
@soulgalore good plan. I'm more than happy to start raising a few PR's too.

**Comment by soulgalore** [comment]
@Nooshu I've pushed the changes I've done during the weekend. It's a little bit better structure now, it still needs love but I think it's safe now to do some PRs.

Missing now is better generic comment section (as your suggestion) and having an auto changed page title (we should be able to do something smart with the info we have in the HAR files).

**Comment by Nooshu** [comment]
Great work @soulgalore! Above and beyond the original issue raised. I'm looking forward to seeing the other ideas that develop off the back of this work.

**Comment by soulgalore** [comment]
I think we we can safely close this now. I've updated the README to reflect the changes. What was extra good was the extra goodies we got from this :)
