### ISSUE TITLE
Error message not obvious/formatted

### ISSUE THREAD

**Issue by staabm** [sitespeedio/compare#5]
entered 2 urls, clicked "compare" button.

devtools show that 2 ajax request are fired and got http200, but the UI itself doesnt present any information/compare result.

its also not visiual to the enduser that the "process" started when clicking the "compare" button

edit: after a 2nd look I see a "NetworkError when attempting to fetch resource." in the website (which was not visible enough to indicate a error). since the devtools tell me everything went ok, I guess this errormsg is wrong.

![grafik](https://user-images.githubusercontent.com/120441/30154064-041f44a8-93b9-11e7-9d98-1f84bc7d1c14.png)

**Comment by soulgalore** [comment]
Hi @staabm 
thanks for filing the bug.

A couple of things then:
* Make the error message stand out more so it's easy to see
* Add info for the user to check the console (we log the full error there). If you check your console error, do you get something there?
* A nice way to show something if the process from pressing the button takes more than Xs so you know that we are fetching/parsing the data (I need help with that :) ).

Best
Peter

**Comment by staabm** [comment]
> Add info for the user to check the console (we log the full error there). If you check your console error, do you get something there?

Tried on ipad, no console available :)

**Comment by soulgalore** [comment]
I think we catch all errors now, output in a red field and also logs to the console.
