### ISSUE TITLE
Add a service worker for Offline HAR comparison 

### ISSUE THREAD

**Issue by Nooshu** [sitespeedio/compare#54]
I'd like to look at integrating [Workbox](https://developers.google.com/web/tools/workbox/) into the development workflow and add a service worker to compare. This will allow the application to have an offline mode and also speed up performance for regular users.

Since the site currently consists of a single file this should be super simple to do.

The user need? I do lots of work on the train where wi-fi is flakey and slow. So as a user, I need this :)

**Comment by soulgalore** [comment]
Two things: I really like the idea with a service worker and offline support! For Workbox: It will generate the service worker fully or does it only works with importing the workbox js from Google? Want to avoid doing request to Google for privacy reasons.

**Comment by Nooshu** [comment]
There are t ways to do it.

1. Import workbox from the Google CDN as you mentioned
2. Include a specific version of Workbox in the local build

If we use the [generateSW](https://developers.google.com/web/tools/workbox/modules/workbox-build#generatesw_mode) method we get this for free when using the `importWorkboxFrom` and `local` option. So I will use that when I come to implementing it. Going back to Google every time does seem a little overkill.

**Comment by soulgalore** [comment]
Cool :)
