### ISSUE TITLE
Service worker cache local changes in the HTML

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/compare#60]
Hi @Nooshu 
I tried to do a couple of changes locally in the HTML file but the new output was never reloaded. I think (but I haven't investigated) that the service worker caches the HTML for the old version?

This is my workflow:
1. I edit the index.html file
2. I check my console and it looks right:
```
[07:52:11] Finished 'copyHtmlTask' after 6.61 ms
[Browsersync] Reloading Browsers...
```
3. I check into the build folder and there is the new change.
4. But in the browser (even with a refresh) the view source gives me the old HTML.

When you have the time, can you check that you get the same thing? 

Best
Peter

**Comment by Nooshu** [comment]
Hi @soulgalore, a [PR](https://github.com/sitespeedio/compare/pull/61) has been opened with the changes. I've tested to see if the SW is regenerated on file change and it looks to be working for me.

For local development it may also be worth ticking "update on reload" in Chrome:

![screen shot 2018-11-01 at 09 55 10](https://user-images.githubusercontent.com/1223960/47845202-4ec62a00-ddbc-11e8-96f1-e6f5584a5869.png)

If it becomes too cumbersome, let me know and we can disable for local development and only generate a new SW on the production build.

**Comment by soulgalore** [comment]
Ah great thanks for the fix!
