### ISSUE TITLE
Use HAR files name instead of HAR1 and HAR2

### ISSUE THREAD

**Issue by kazazor** [sitespeedio/compare#70]
The compare tool is GREAT!

I suggest taking the files names from the HAR files instead of using `HAR2` and `HAR2`. It's harder to understand which option is which.

For example, I would like to compare the `before.hr.gz` with `new.hr.gz` but they appear as `har1` and `har2` so just to make sure which is which I uploaded them 1 by one in the tool again.

## More info
I used the online one and not deployed one of my own.

**Comment by soulgalore** [comment]
Thanks for the kind words!

Yeah I think since some tools name them the same name, we need have some kind of flexibility there. Right now we first look for "Label" then use HAR1/HAR2 but if it easy and we have different names, we could show (part) of the name.

**Comment by soulgalore** [comment]
This was implemented in https://github.com/sitespeedio/compare/pull/119 but it only use the file name if you upload two HARs.
