### ISSUE TITLE
Using query params for the HAR files does not work

### ISSUE THREAD

**Issue by kazazor** [sitespeedio/compare#71]
I would like to report a bug.

I could only make the tool work if I manually upload the files via the UI. The option of adding the HR files via URL does not work.

It does not work if I do it manually or if I use the UI text fields to add the URLs.
I tried downloading the files with the URL and it's open and working so everything should have worked.

## Reproduce it

Just use and 1 HAR files in the URL at compare.sitespeed.io

## More info
I used the online one and not deployed one of my own.

**Comment by soulgalore** [comment]
Have you setup CORS on the server that share the files (https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)? Check in the console of your browser, you should get an error if it is not setup.

**Comment by kazazor** [comment]
You're right!

Maybe worth mentioning it in the docs? https://www.sitespeed.io/documentation/compare/

In any case I'll close the issue now.

**Comment by soulgalore** [comment]
Yes agree, I pushed it now.
