### ISSUE TITLE
Cannot read property 'onLoad' of undefined

### ISSUE THREAD

**Issue by hakimelek** [sitespeedio/compare#72]
I am trying to load an har file but I am getting this error message every time I upload a file, it doesn't matter what site it is.

Safari:
```
undefined is not an object (evaluating 'p[n.pageref].onLoad')
```

Chrome: 
```
 TypeError: Cannot read property 'onLoad' of undefined
    at combined-6c771034ee.js:21
    at Array.forEach (<anonymous>)
    at Object.convert (combined-6c771034ee.js:21)
    at Object.convertIndex (combined-6c771034ee.js:21)
    at generate (combined-6c771034ee.js:937)
    at readHar.then.har (combined-6c771034ee.js:130)
```

**Comment by soulgalore** [comment]
Hi @hakimelek thanks for creating the issue. Can you please share the HAR file so I can recreate the issue? 

Thanks
Peter

**Comment by hakimelek** [comment]
Hi @soulgalore, 

Here is [one](https://drive.google.com/file/d/1SUP55vGRRPVkf5f3sdSDh2iconkcms7L/view?usp=sharing). I just opened the network tab of priceline.com and hit "save all as HAR with content".

**Comment by soulgalore** [comment]
Hi @hakimelek ok cool, can you add it as a [gist](https://gist.github.com) instead, I don't have access to Google Drive. Have you validate the HAR file (easiest is to use http://www.softwareishard.com/har/viewer/ that check that it's valid), some browser create invalid HARs. Not saying we should parse it too but it could maybe be an upstream issue too.

Best
Peter

**Comment by hakimelek** [comment]
Oh sorry about that, I created a [gist](https://gist.github.com/hakimelek/54732b0eb6431a21866375c65e8b2d1a#file-priceline-com-har) with the content. I was also able to view with the HAR viewer. I think the issue is in the JS of the website since it doesn't seem that the website is making any http call when the file is uploaded.

**Comment by soulgalore** [comment]
Thanks for sharing the HAR! It worked when I tried it locally and when I checked compare.sitespeed.io wasn't running the latest version, so I re-deployed on Netlify and now it works. If you can verify too @hakimelek before I close the issue that would be great.

Thanks
Peter

**Comment by hakimelek** [comment]
Wonderful! It works well now. Thanks again!

**Comment by soulgalore** [comment]
Great!
