### ISSUE TITLE
Chrome 72.0.3626.121: Cannot read property 'Painting' of undefined

### ISSUE THREAD

**Issue by deftdawg** [sitespeedio/compare#84]
Har files generated with Chrome 72 fail with the error message: Cannot read property 'Painting' of undefined

```javascript
!function(e,t) ... // fails in the compressed code on line 15 of combined.js
```

Files are valid if run against http://www.softwareishard.com/har/viewer/

[chrome-www.google.ca.har.txt](https://github.com/sitespeedio/compare/files/3233592/chrome-www.google.ca.har.txt)
[chrome-www.google.com.har.txt](https://github.com/sitespeedio/compare/files/3233593/chrome-www.google.com.har.txt)

**Comment by soulgalore** [comment]
Hi @deftdawg thanks for sharing the HAR, let me have a look!

Best
Peter

**Comment by deftdawg** [comment]
No worries, was sanity checking with a couple of really simple captures after my really complicated IE ones failed...   Figured I'd try chrome since I have more faith in it to produce well formed output.  😄

**Comment by soulgalore** [comment]
This is fixed now, it seems that the you may need to do a hard refresh though, I'll look into that later.

Best
Peter

**Comment by deftdawg** [comment]
Yep you fixed it. I got a prompt on the page saying "A new version exists 'reload' / 'dismiss'", reloaded and retried the chrome HARs and they worked...   Retested IE ones as well, they still fail with same error (#83).

**Comment by soulgalore** [comment]
Yeah I haven't done something for the IE problem, I'm saving that for later :)

**Comment by deftdawg** [comment]
Understandable, it pains me that I'm forced to deal with IE at all, so I wouldn't blame you if you save it for the day IE goes away altogether.  😆

**Comment by taphyoe** [comment]
I have to use IE11 and found the problem with the format. 

IE11 HAR file doesn't have pages section and Page Ref 

"pages":

"pageref": "page_1"

I just did a quick fix on my har file inroder to work. I will see if I can fix the code later. Just dropping here if someone want to fix it. :D 

Thanks!
